# Generated by Django 6.0.6 on 2026-06-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=100)),
                ('tipo_evento', models.CharField(max_length=50)),
                ('fecha_evento', models.DateField()),
                ('numero_personas', models.IntegerField()),
                ('sabor_interes', models.CharField(max_length=50)),
                ('tamano', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('entrega_domicilio', models.BooleanField(default=False)),
                ('acepta_privacidad', models.BooleanField(default=False)),
            ],
        ),
    ]
