# Generated by Django 6.0.6 on 2026-06-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_fecha_registro_alter_lead_correo_electronico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='acepta_privacidad',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='correo_electronico',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='entrega_domicilio',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='fecha_evento',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='numero_personas',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='sabor_interes',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='tamano',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='tipo_evento',
        ),
        migrations.AlterModelTable(
            name='lead',
            table='leads',
        ),
    ]
